"""Build and verify a minimal, immutable Optima referee source release.

An OCI launch must not bind-mount the validator checkout.  Besides exposing git
metadata, work logs, credentials and unrelated experiments, a checkout can contain
generated bytecode or filesystem objects such as Unix sockets.  This module turns a
trusted Optima source package into a small content-addressed release containing only
Python source and explicitly approved package data.

The builder is deliberately independent of the OCI launcher.  Controller code can
materialize a release once, verify its two identities, and pass ``release.root`` as
the launch profile's ``source_dir``.  Every source read uses ``O_NOFOLLOW`` and is
checked before and after reading; every published file is read-only.  Publication is
an atomic rename within a validator-owned cache directory.
"""

from __future__ import annotations

import ast
import errno
import hashlib
import json
import os
import re
import shutil
import stat
import tempfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Mapping


RELEASE_SCHEMA = "optima.referee-source-release.v1"
RELEASE_POLICY = "optima-python-source-and-explicit-data.v1"
RELEASE_MANIFEST = "optima-referee-release.json"

# These are required by both the normal engine worker and the isolated prebuild
# worker.  The rest of the package is copied as Python source because imports vary
# by slot, arena and fidelity lane.
RUNTIME_PACKAGE_ROOTS = ("optima", "optima_kernels")

REQUIRED_RUNTIME_FILES = frozenset(
    {
        "optima/__init__.py",
        "optima/eval/__init__.py",
        "optima/eval/oci_prebuild.py",
        "optima/eval/oci_protocol.py",
        "optima/eval/oci_session_protocol.py",
        "optima/eval/oci_session_worker.py",
        "optima/eval/seccomp_moby_v0_2_1.json",
        "optima/eval/oci_site/sitecustomize.py",
        "optima/eval/oci_worker.py",
        "optima_kernels/__init__.py",
        "optima_kernels/override.py",
        "optima_kernels/collective/fused_ar_rmsnorm_sm103.cu",
    }
)

DEFAULT_PACKAGE_DATA: tuple[str, ...] = (
    "optima/eval/seccomp_moby_v0_2_1.json",
    "optima_kernels/collective/fused_ar_rmsnorm_sm103.cu",
)
DEFAULT_MAX_FILES = 2_048
DEFAULT_MAX_FILE_BYTES = 32 * 1024 * 1024
DEFAULT_MAX_TOTAL_BYTES = 256 * 1024 * 1024
DEFAULT_MAX_TREE_ENTRIES = 8_192
DEFAULT_MAX_PATH_DEPTH = 16

_SHA256 = re.compile(r"sha256:[0-9a-f]{64}\Z")
_SAFE_COMPONENT = re.compile(r"[A-Za-z0-9_][A-Za-z0-9_.-]*\Z")
_NOFOLLOW = getattr(os, "O_NOFOLLOW", None)
_CLOEXEC = getattr(os, "O_CLOEXEC", 0)
_DIRECTORY = getattr(os, "O_DIRECTORY", 0)
_RECEIPT_MODULE = "optima/referee_release.py"
_RECEIPT_CONSTANTS = (
    "APPROVED_REFEREE_SOURCE_DIGEST",
    "APPROVED_REFEREE_TREE_DIGEST",
)
_ZERO_RECEIPT = "sha256:" + "0" * 64


class RefereeReleaseError(RuntimeError):
    """A referee source tree is unsafe, incomplete, or has the wrong identity."""


@dataclass(frozen=True, slots=True)
class ReleaseFile:
    """One regular file covered by the canonical release identity."""

    path: str
    size: int
    sha256: str

    def as_manifest_row(self) -> dict[str, Any]:
        return {"path": self.path, "sha256": self.sha256, "size": self.size}


@dataclass(frozen=True, slots=True)
class RefereeSourceRelease:
    """A verified, content-addressed referee release ready for a read-only bind."""

    root: Path
    tree_digest: str
    referee_source_digest: str
    files: tuple[ReleaseFile, ...]
    package_data: tuple[str, ...]

    @property
    def manifest_path(self) -> Path:
        return self.root / RELEASE_MANIFEST


def _canonical_json(value: Mapping[str, Any]) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("ascii")


def _strict_json_object(raw: bytes, *, source: Path) -> Mapping[str, Any]:
    def pairs(values: list[tuple[str, Any]]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, value in values:
            if key in result:
                raise RefereeReleaseError(
                    f"release manifest contains duplicate key {key!r}: {source}"
                )
            result[key] = value
        return result

    try:
        value = json.loads(raw, object_pairs_hook=pairs)
    except RefereeReleaseError:
        raise
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise RefereeReleaseError(f"malformed release manifest {source}: {exc}") from None
    if not isinstance(value, dict):
        raise RefereeReleaseError(f"release manifest must be a JSON object: {source}")
    return value


def _canonical_root(value: str | os.PathLike[str], *, name: str, create: bool) -> Path:
    raw = Path(value)
    if not raw.is_absolute():
        raise RefereeReleaseError(f"{name} must be an absolute path")
    if create:
        try:
            raw.mkdir(mode=0o700, parents=True, exist_ok=True)
        except OSError as exc:
            raise RefereeReleaseError(f"cannot create {name}: {exc}") from None
    try:
        before = raw.lstat()
    except OSError as exc:
        raise RefereeReleaseError(f"cannot inspect {name}: {exc}") from None
    if stat.S_ISLNK(before.st_mode):
        raise RefereeReleaseError(f"{name} must not be a symlink: {raw}")
    if not stat.S_ISDIR(before.st_mode):
        raise RefereeReleaseError(f"{name} must be a directory: {raw}")
    try:
        root = raw.resolve(strict=True)
        after = root.stat()
    except (OSError, RuntimeError) as exc:
        raise RefereeReleaseError(f"cannot resolve {name}: {exc}") from None
    if (before.st_dev, before.st_ino) != (after.st_dev, after.st_ino):
        raise RefereeReleaseError(f"{name} changed while it was resolved: {raw}")
    return root


def _validate_component(name: str, *, path: Path) -> None:
    if name in {"", ".", ".."} or _SAFE_COMPONENT.fullmatch(name) is None:
        raise RefereeReleaseError(f"unsafe path component {name!r} below {path}")


def _normalize_package_data(values: Iterable[str]) -> frozenset[str]:
    result: set[str] = set()
    for value in values:
        if not isinstance(value, str):
            raise RefereeReleaseError("package_data entries must be strings")
        pure = PurePosixPath(value)
        if (
            not value
            or pure.is_absolute()
            or value != pure.as_posix()
            or ".." in pure.parts
            or not pure.parts
            or pure.parts[0] not in RUNTIME_PACKAGE_ROOTS
            or value.endswith(".py")
            or value == RELEASE_MANIFEST
        ):
            raise RefereeReleaseError(
                "package_data entry must be an exact non-Python path below a runtime "
                f"package: {value!r}"
            )
        for component in pure.parts:
            _validate_component(component, path=Path(value))
        if value in result:
            raise RefereeReleaseError(f"duplicate package_data entry {value!r}")
        result.add(value)
    return frozenset(result)


def _read_regular_nofollow(path: Path, *, max_bytes: int) -> bytes:
    if _NOFOLLOW is None:
        raise RefereeReleaseError("this platform lacks O_NOFOLLOW")
    try:
        fd = os.open(path, os.O_RDONLY | _CLOEXEC | _NOFOLLOW)
    except OSError as exc:
        raise RefereeReleaseError(
            f"cannot open regular file without following links {path}: {exc}"
        ) from None
    try:
        first = os.fstat(fd)
        if (
            not stat.S_ISREG(first.st_mode)
            or first.st_nlink != 1
            or first.st_uid != os.geteuid()
        ):
            raise RefereeReleaseError(f"release input is not a regular file: {path}")
        if first.st_size < 0 or first.st_size > max_bytes:
            raise RefereeReleaseError(
                f"release input exceeds {max_bytes} bytes: {path} ({first.st_size})"
            )
        chunks: list[bytes] = []
        remaining = first.st_size
        while remaining:
            chunk = os.read(fd, min(1024 * 1024, remaining))
            if not chunk:
                raise RefereeReleaseError(f"release input was truncated while reading: {path}")
            chunks.append(chunk)
            remaining -= len(chunk)
        if os.read(fd, 1):
            raise RefereeReleaseError(f"release input grew while reading: {path}")
        second = os.fstat(fd)
        stable_fields = (
            "st_dev", "st_ino", "st_mode", "st_nlink", "st_uid", "st_gid",
            "st_size", "st_mtime_ns", "st_ctime_ns",
        )
        if any(getattr(first, field) != getattr(second, field) for field in stable_fields):
            raise RefereeReleaseError(f"release input changed while reading: {path}")
        payload = b"".join(chunks)
        if len(payload) != first.st_size:
            raise RefereeReleaseError(f"release input size changed while reading: {path}")
        return payload
    finally:
        os.close(fd)


def _scan_ignored_bytecode(directory: Path) -> None:
    """Allow ordinary pycache noise without trusting or copying any of it."""

    try:
        with os.scandir(directory) as iterator:
            entries = sorted(iterator, key=lambda entry: entry.name)
    except OSError as exc:
        raise RefereeReleaseError(f"cannot scan bytecode cache {directory}: {exc}") from None
    if len(entries) > DEFAULT_MAX_TREE_ENTRIES:
        raise RefereeReleaseError(f"bytecode cache has too many entries: {directory}")
    for entry in entries:
        _validate_component(entry.name, path=directory)
        try:
            info = entry.stat(follow_symlinks=False)
        except OSError as exc:
            raise RefereeReleaseError(f"cannot inspect {entry.path}: {exc}") from None
        if stat.S_ISLNK(info.st_mode):
            raise RefereeReleaseError(f"symlink is forbidden in referee source: {entry.path}")
        if not stat.S_ISREG(info.st_mode) or not entry.name.endswith(".pyc"):
            raise RefereeReleaseError(
                f"unapproved entry in referee bytecode cache: {entry.path}"
            )


def _collect_source_files(
    source_root: Path,
    *,
    package_data: frozenset[str],
    max_files: int,
    max_file_bytes: int,
    max_total_bytes: int,
) -> dict[str, bytes]:
    result: dict[str, bytes] = {}
    folded_paths: dict[str, str] = {}
    total = 0
    visited_entries = 0

    def walk(directory: Path, relative_dir: PurePosixPath) -> None:
        nonlocal total, visited_entries
        if len(relative_dir.parts) > DEFAULT_MAX_PATH_DEPTH:
            raise RefereeReleaseError(f"referee source path is too deep: {relative_dir}")
        try:
            with os.scandir(directory) as iterator:
                entries = sorted(iterator, key=lambda entry: entry.name)
        except OSError as exc:
            raise RefereeReleaseError(f"cannot scan referee source {directory}: {exc}") from None
        visited_entries += len(entries)
        if visited_entries > DEFAULT_MAX_TREE_ENTRIES:
            raise RefereeReleaseError(
                f"referee source exceeds {DEFAULT_MAX_TREE_ENTRIES} filesystem entries"
            )
        for entry in entries:
            _validate_component(entry.name, path=directory)
            path = Path(entry.path)
            relative = relative_dir / entry.name
            relative_text = relative.as_posix()
            try:
                info = entry.stat(follow_symlinks=False)
            except OSError as exc:
                raise RefereeReleaseError(f"cannot inspect referee source {path}: {exc}") from None
            if stat.S_ISLNK(info.st_mode):
                raise RefereeReleaseError(f"symlink is forbidden in referee source: {path}")
            if stat.S_ISDIR(info.st_mode):
                if entry.name == "__pycache__":
                    _scan_ignored_bytecode(path)
                else:
                    walk(path, relative)
                continue
            if not stat.S_ISREG(info.st_mode):
                raise RefereeReleaseError(
                    f"non-regular filesystem object is forbidden in referee source: {path}"
                )
            approved = relative_text.endswith(".py") or relative_text in package_data
            if not approved:
                raise RefereeReleaseError(f"unapproved referee package file: {relative_text}")
            folded = relative_text.casefold()
            if folded in folded_paths:
                raise RefereeReleaseError(
                    "case-colliding referee paths are not portable: "
                    f"{folded_paths[folded]!r} and {relative_text!r}"
                )
            payload = _read_regular_nofollow(path, max_bytes=max_file_bytes)
            total += len(payload)
            if len(result) >= max_files:
                raise RefereeReleaseError(f"referee release exceeds {max_files} files")
            if total > max_total_bytes:
                raise RefereeReleaseError(
                    f"referee release exceeds {max_total_bytes} total bytes"
                )
            folded_paths[folded] = relative_text
            result[relative_text] = payload

    for package_name in RUNTIME_PACKAGE_ROOTS:
        package_root = source_root / package_name
        try:
            package_info = package_root.lstat()
        except OSError as exc:
            raise RefereeReleaseError(
                f"source has no {package_name} runtime package: {exc}"
            ) from None
        if stat.S_ISLNK(package_info.st_mode) or not stat.S_ISDIR(package_info.st_mode):
            raise RefereeReleaseError(
                f"source {package_name} package must be a real directory"
            )
        walk(package_root, PurePosixPath(package_name))
    missing_data = package_data.difference(result)
    if missing_data:
        raise RefereeReleaseError(
            f"approved package_data files are missing: {sorted(missing_data)!r}"
        )
    missing_runtime = REQUIRED_RUNTIME_FILES.difference(result)
    if missing_runtime:
        raise RefereeReleaseError(
            f"referee source lacks required OCI runtime files: {sorted(missing_runtime)!r}"
        )
    return result


def _sha256(payload: bytes) -> str:
    return f"sha256:{hashlib.sha256(payload).hexdigest()}"


def _receipt_literal_spans(payload: bytes) -> dict[str, tuple[int, int, str]]:
    """Locate only the two approved digest string literals in referee_release.py."""

    try:
        text = payload.decode("utf-8")
        tree = ast.parse(text, filename=_RECEIPT_MODULE)
    except (UnicodeDecodeError, SyntaxError) as exc:
        raise RefereeReleaseError(f"cannot parse {_RECEIPT_MODULE}: {exc}") from None
    lines = payload.splitlines(keepends=True)
    starts: list[int] = []
    offset = 0
    for line in lines:
        starts.append(offset)
        offset += len(line)
    found: dict[str, tuple[int, int, str]] = {}
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        if len(targets) != 1 or not isinstance(targets[0], ast.Name):
            continue
        name = targets[0].id
        if name not in _RECEIPT_CONSTANTS:
            continue
        value = node.value
        if (
            name in found
            or not isinstance(value, ast.Constant)
            or not isinstance(value.value, str)
            or value.end_lineno is None
            or value.end_col_offset is None
        ):
            raise RefereeReleaseError(f"{name} must be one literal string assignment")
        literal_value = value.value
        if _SHA256.fullmatch(literal_value) is None:
            raise RefereeReleaseError(f"{name} must be a sha256 content identity")
        start = starts[value.lineno - 1] + value.col_offset
        end = starts[value.end_lineno - 1] + value.end_col_offset
        segment = payload[start:end]
        needle = literal_value.encode("ascii")
        if segment.count(needle) != 1:
            raise RefereeReleaseError(
                f"{name} must use one non-concatenated ASCII digest literal"
            )
        inner = segment.index(needle)
        found[name] = (start + inner, start + inner + len(needle), literal_value)
    if set(found) != set(_RECEIPT_CONSTANTS):
        raise RefereeReleaseError(
            f"{_RECEIPT_MODULE} must define exactly {_RECEIPT_CONSTANTS!r}"
        )
    return found


def _replace_receipt_literals(
    payload: bytes, *, source_digest: str, tree_digest: str,
) -> bytes:
    replacements = {
        "APPROVED_REFEREE_SOURCE_DIGEST": source_digest,
        "APPROVED_REFEREE_TREE_DIGEST": tree_digest,
    }
    spans = _receipt_literal_spans(payload)
    result = bytearray(payload)
    for name, (start, end, _value) in sorted(
        spans.items(), key=lambda item: item[1][0], reverse=True
    ):
        replacement = replacements[name].encode("ascii")
        if len(replacement) != end - start:
            raise RefereeReleaseError("referee receipt replacement changed source length")
        result[start:end] = replacement
    return bytes(result)


def _normalized_release_payload(path: str, payload: bytes) -> bytes:
    if path != _RECEIPT_MODULE:
        return payload
    return _replace_receipt_literals(
        payload, source_digest=_ZERO_RECEIPT, tree_digest=_ZERO_RECEIPT
    )


def _validate_or_materialize_receipt_module(
    payload: bytes, *, source_digest: str, tree_digest: str,
) -> bytes:
    spans = _receipt_literal_spans(payload)
    observed = {name: value for name, (_start, _end, value) in spans.items()}
    expected = {
        "APPROVED_REFEREE_SOURCE_DIGEST": source_digest,
        "APPROVED_REFEREE_TREE_DIGEST": tree_digest,
    }
    placeholders = {name: _ZERO_RECEIPT for name in _RECEIPT_CONSTANTS}
    if observed not in (expected, placeholders):
        raise RefereeReleaseError(
            "referee_release.py approved digest literals are neither placeholders "
            "nor the computed release identities"
        )
    return _replace_receipt_literals(
        payload, source_digest=source_digest, tree_digest=tree_digest
    )


def _referee_source_digest(payloads: Mapping[str, bytes]) -> str:
    """Match ``arenas.referee_source_digest`` without unsafe Path reads."""

    digest = hashlib.sha256()
    rows: list[tuple[str, bytes]] = []
    for full_path, payload in payloads.items():
        pure = PurePosixPath(full_path)
        if (
            pure.parts[0] != "optima"
            or pure.suffix != ".py"
            or pure.name == "referee_release.py"
        ):
            continue
        try:
            relative = pure.relative_to("optima").as_posix()
        except ValueError:
            raise RefereeReleaseError(f"release file escaped optima/: {full_path!r}") from None
        rows.append((relative, payload))
    if not rows:
        raise RefereeReleaseError("referee release contains no Python source")
    for relative_text, payload in sorted(rows):
        relative = relative_text.encode("utf-8")
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        digest.update(len(payload).to_bytes(8, "big"))
        digest.update(payload)
    return f"sha256:{digest.hexdigest()}"


def _release_identity(
    payloads: Mapping[str, bytes],
    *,
    package_data: frozenset[str],
) -> tuple[tuple[ReleaseFile, ...], str, str, dict[str, Any]]:
    files = tuple(
        ReleaseFile(
            path=path,
            size=len(payload),
            sha256=_sha256(_normalized_release_payload(path, payload)),
        )
        for path, payload in sorted(payloads.items())
    )
    source_digest = _referee_source_digest(payloads)
    identity: dict[str, Any] = {
        "files": [entry.as_manifest_row() for entry in files],
        "package_data": sorted(package_data),
        "policy": RELEASE_POLICY,
        "schema": RELEASE_SCHEMA,
    }
    tree_digest = _sha256(_canonical_json(identity))
    manifest = {
        **identity,
        "referee_source_digest": source_digest,
        "tree_digest": tree_digest,
    }
    return files, tree_digest, source_digest, manifest


def _write_new_file(path: Path, payload: bytes) -> None:
    if _NOFOLLOW is None:
        raise RefereeReleaseError("this platform lacks O_NOFOLLOW")
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | _CLOEXEC | _NOFOLLOW
    try:
        fd = os.open(path, flags, 0o600)
    except OSError as exc:
        raise RefereeReleaseError(f"cannot create release file {path}: {exc}") from None
    try:
        view = memoryview(payload)
        while view:
            written = os.write(fd, view)
            if written <= 0:
                raise RefereeReleaseError(f"short write creating release file {path}")
            view = view[written:]
        os.fchmod(fd, 0o444)
        os.fsync(fd)
    finally:
        os.close(fd)


def _sync_directory(path: Path) -> None:
    try:
        fd = os.open(path, os.O_RDONLY | _CLOEXEC | _DIRECTORY)
    except OSError as exc:
        raise RefereeReleaseError(f"cannot open release directory for sync {path}: {exc}") from None
    try:
        try:
            os.fsync(fd)
        except OSError as exc:
            if exc.errno not in {errno.EINVAL, getattr(errno, "ENOTSUP", errno.EINVAL)}:
                raise
    finally:
        os.close(fd)


def _freeze_tree(root: Path) -> None:
    directories = [root]
    for directory, child_dirs, _ in os.walk(root, topdown=True, followlinks=False):
        base = Path(directory)
        for child in child_dirs:
            child_path = base / child
            info = child_path.lstat()
            if stat.S_ISLNK(info.st_mode) or not stat.S_ISDIR(info.st_mode):
                raise RefereeReleaseError(
                    f"unsafe directory appeared in staging tree: {child_path}"
                )
            directories.append(child_path)
    for directory in sorted(directories, key=lambda path: len(path.parts), reverse=True):
        _sync_directory(directory)
        os.chmod(directory, 0o555, follow_symlinks=False)


def _remove_private_tree(root: Path) -> None:
    if not os.path.lexists(root):
        return
    for directory, child_dirs, _ in os.walk(root, topdown=False, followlinks=False):
        for child in child_dirs:
            path = Path(directory) / child
            if not path.is_symlink():
                try:
                    os.chmod(path, 0o700, follow_symlinks=False)
                except OSError:
                    pass
        try:
            os.chmod(directory, 0o700, follow_symlinks=False)
        except OSError:
            pass
    shutil.rmtree(root)


def build_referee_source_release(
    source_root: str | os.PathLike[str],
    publish_root: str | os.PathLike[str],
    *,
    package_data: Iterable[str] = (),
    max_files: int = DEFAULT_MAX_FILES,
    max_file_bytes: int = DEFAULT_MAX_FILE_BYTES,
    max_total_bytes: int = DEFAULT_MAX_TOTAL_BYTES,
    expected_tree_digest: str | None = None,
    expected_referee_source_digest: str | None = None,
) -> RefereeSourceRelease:
    """Sanitize, content-address, atomically publish, and re-verify Optima source.

    ``source_root`` is the checkout/install root containing ``optima/`` and
    ``optima_kernels/``.
    ``publish_root`` must be validator-owned and not group/world writable.  A
    successful result can be reused by identity across launches.
    """

    for name, value in (
        ("max_files", max_files),
        ("max_file_bytes", max_file_bytes),
        ("max_total_bytes", max_total_bytes),
    ):
        if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
            raise RefereeReleaseError(f"{name} must be a positive integer")
    if max_files > DEFAULT_MAX_FILES:
        raise RefereeReleaseError(f"max_files may not exceed hard cap {DEFAULT_MAX_FILES}")
    if max_file_bytes > DEFAULT_MAX_FILE_BYTES:
        raise RefereeReleaseError(
            f"max_file_bytes may not exceed hard cap {DEFAULT_MAX_FILE_BYTES}"
        )
    if max_total_bytes > DEFAULT_MAX_TOTAL_BYTES:
        raise RefereeReleaseError(
            f"max_total_bytes may not exceed hard cap {DEFAULT_MAX_TOTAL_BYTES}"
        )
    for name, value in (
        ("expected_tree_digest", expected_tree_digest),
        ("expected_referee_source_digest", expected_referee_source_digest),
    ):
        if value is not None and (
            not isinstance(value, str) or _SHA256.fullmatch(value) is None
        ):
            raise RefereeReleaseError(f"{name} must be a sha256 content identity")
    source = _canonical_root(source_root, name="source_root", create=False)
    publication = _canonical_root(publish_root, name="publish_root", create=True)
    publication_info = publication.stat()
    if publication_info.st_uid != os.geteuid():
        raise RefereeReleaseError("publish_root must be owned by the validator user")
    if publication_info.st_mode & 0o022:
        raise RefereeReleaseError("publish_root must not be group/world writable")
    for package_name in RUNTIME_PACKAGE_ROOTS:
        try:
            publication.relative_to(source / package_name)
        except ValueError:
            continue
        raise RefereeReleaseError(
            f"publish_root must not be inside the source {package_name} package"
        )

    approved_data = _normalize_package_data(DEFAULT_PACKAGE_DATA) | _normalize_package_data(
        package_data
    )
    payloads = _collect_source_files(
        source,
        package_data=approved_data,
        max_files=max_files,
        max_file_bytes=max_file_bytes,
        max_total_bytes=max_total_bytes,
    )
    _, tree_digest, source_digest, manifest = _release_identity(
        payloads, package_data=approved_data
    )
    if _RECEIPT_MODULE not in payloads:
        raise RefereeReleaseError(f"referee source lacks {_RECEIPT_MODULE}")
    materialized_payloads = dict(payloads)
    materialized_payloads[_RECEIPT_MODULE] = _validate_or_materialize_receipt_module(
        payloads[_RECEIPT_MODULE],
        source_digest=source_digest,
        tree_digest=tree_digest,
    )
    if expected_tree_digest is not None and tree_digest != expected_tree_digest:
        raise RefereeReleaseError(
            f"referee tree identity mismatch: {tree_digest!r} != {expected_tree_digest!r}"
        )
    if (
        expected_referee_source_digest is not None
        and source_digest != expected_referee_source_digest
    ):
        raise RefereeReleaseError(
            "referee source identity mismatch: "
            f"{source_digest!r} != {expected_referee_source_digest!r}"
        )
    final = publication / f"sha256-{tree_digest.removeprefix('sha256:')}"
    stage = Path(tempfile.mkdtemp(prefix=".referee-build-", dir=publication))
    try:
        for relative, payload in sorted(materialized_payloads.items()):
            destination = stage / PurePosixPath(relative)
            destination.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
            _write_new_file(destination, payload)
        manifest_payload = _canonical_json(manifest) + b"\n"
        _write_new_file(stage / RELEASE_MANIFEST, manifest_payload)
        _freeze_tree(stage)

        if os.path.lexists(final):
            existing = verify_referee_source_release(
                final,
                expected_tree_digest=tree_digest,
                expected_referee_source_digest=source_digest,
                package_data=approved_data,
            )
            _remove_private_tree(stage)
            return existing
        try:
            os.rename(stage, final)
        except OSError as exc:
            # Concurrent builders of the same identity are harmless.  Never trust
            # the winner merely because it occupies the content-addressed name.
            destination_won_race = os.path.lexists(final) and exc.errno in {
                errno.EACCES,
                errno.EEXIST,
                errno.ENOTEMPTY,
                errno.EPERM,
            }
            if not destination_won_race:
                raise RefereeReleaseError(f"atomic release publication failed: {exc}") from None
            existing = verify_referee_source_release(
                final,
                expected_tree_digest=tree_digest,
                expected_referee_source_digest=source_digest,
                package_data=approved_data,
            )
            _remove_private_tree(stage)
            return existing
        _sync_directory(publication)
        return verify_referee_source_release(
            final,
            expected_tree_digest=tree_digest,
            expected_referee_source_digest=source_digest,
            package_data=approved_data,
        )
    except Exception:
        _remove_private_tree(stage)
        raise


def _manifest_release_files(
    raw_files: Any, *, package_data: frozenset[str]
) -> tuple[ReleaseFile, ...]:
    if not isinstance(raw_files, list) or not raw_files:
        raise RefereeReleaseError("release manifest files must be a non-empty list")
    if len(raw_files) > DEFAULT_MAX_FILES:
        raise RefereeReleaseError("release manifest exceeds the hard file-count cap")
    result: list[ReleaseFile] = []
    seen: set[str] = set()
    folded: set[str] = set()
    total_size = 0
    for raw in raw_files:
        if not isinstance(raw, dict) or set(raw) != {"path", "sha256", "size"}:
            raise RefereeReleaseError("release manifest has a malformed file row")
        path = raw["path"]
        size = raw["size"]
        digest = raw["sha256"]
        if not isinstance(path, str):
            raise RefereeReleaseError("release manifest file path must be a string")
        pure = PurePosixPath(path)
        if (
            pure.is_absolute()
            or path != pure.as_posix()
            or not pure.parts
            or pure.parts[0] not in RUNTIME_PACKAGE_ROOTS
            or ".." in pure.parts
            or path == RELEASE_MANIFEST
        ):
            raise RefereeReleaseError(f"unsafe release manifest path {path!r}")
        if not path.endswith(".py") and path not in package_data:
            raise RefereeReleaseError(f"unapproved package data in release manifest: {path!r}")
        for component in pure.parts:
            _validate_component(component, path=Path(path))
        if path in seen or path.casefold() in folded:
            raise RefereeReleaseError(f"duplicate/colliding release manifest path {path!r}")
        if isinstance(size, bool) or not isinstance(size, int) or size < 0:
            raise RefereeReleaseError(f"invalid release file size for {path!r}")
        if size > DEFAULT_MAX_FILE_BYTES:
            raise RefereeReleaseError(f"release file exceeds the hard size cap: {path!r}")
        total_size += size
        if total_size > DEFAULT_MAX_TOTAL_BYTES:
            raise RefereeReleaseError("release manifest exceeds the hard total-size cap")
        if not isinstance(digest, str) or _SHA256.fullmatch(digest) is None:
            raise RefereeReleaseError(f"invalid release file digest for {path!r}")
        seen.add(path)
        folded.add(path.casefold())
        result.append(ReleaseFile(path=path, size=size, sha256=digest))
    if [entry.path for entry in result] != sorted(entry.path for entry in result):
        raise RefereeReleaseError("release manifest files are not canonically sorted")
    return tuple(result)


def _walk_release_tree(root: Path) -> tuple[set[str], set[str]]:
    files: set[str] = set()
    directories: set[str] = set()
    visited_entries = 0
    visited_inodes: set[tuple[int, int]] = set()

    def walk(directory: Path, relative: PurePosixPath | None) -> None:
        nonlocal visited_entries
        if relative is not None and len(relative.parts) > DEFAULT_MAX_PATH_DEPTH:
            raise RefereeReleaseError(f"release path is too deep: {relative}")
        info = directory.lstat()
        if stat.S_ISLNK(info.st_mode) or not stat.S_ISDIR(info.st_mode):
            raise RefereeReleaseError(f"release entry is not a real directory: {directory}")
        if info.st_mode & 0o222:
            raise RefereeReleaseError(f"release directory is writable: {directory}")
        if relative is not None:
            directories.add(relative.as_posix())
        try:
            with os.scandir(directory) as iterator:
                entries = sorted(iterator, key=lambda entry: entry.name)
        except OSError as exc:
            raise RefereeReleaseError(f"cannot scan release directory {directory}: {exc}") from None
        visited_entries += len(entries)
        if visited_entries > DEFAULT_MAX_TREE_ENTRIES:
            raise RefereeReleaseError(
                f"release exceeds {DEFAULT_MAX_TREE_ENTRIES} filesystem entries"
            )
        for entry in entries:
            _validate_component(entry.name, path=directory)
            path = Path(entry.path)
            child_relative = (
                PurePosixPath(entry.name) if relative is None else relative / entry.name
            )
            try:
                child_info = entry.stat(follow_symlinks=False)
            except OSError as exc:
                raise RefereeReleaseError(f"cannot inspect release entry {path}: {exc}") from None
            if stat.S_ISLNK(child_info.st_mode):
                raise RefereeReleaseError(f"symlink is forbidden in referee release: {path}")
            if stat.S_ISDIR(child_info.st_mode):
                walk(path, child_relative)
            elif stat.S_ISREG(child_info.st_mode):
                if child_info.st_mode & 0o222:
                    raise RefereeReleaseError(f"release file is writable: {path}")
                if child_info.st_nlink != 1 or child_info.st_uid != os.geteuid():
                    raise RefereeReleaseError(
                        f"release file is hardlinked or not validator-owned: {path}"
                    )
                inode = (child_info.st_dev, child_info.st_ino)
                if inode in visited_inodes:
                    raise RefereeReleaseError(f"release files alias one inode: {path}")
                visited_inodes.add(inode)
                files.add(child_relative.as_posix())
            else:
                raise RefereeReleaseError(
                    f"non-regular filesystem object is forbidden in referee release: {path}"
                )

    walk(root, None)
    return files, directories


def verify_referee_source_release(
    release_root: str | os.PathLike[str],
    *,
    expected_tree_digest: str | None = None,
    expected_referee_source_digest: str | None = None,
    package_data: Iterable[str] = (),
) -> RefereeSourceRelease:
    """Verify the manifest, exact filesystem shape, bytes, modes, and identities."""

    for name, value in (
        ("expected_tree_digest", expected_tree_digest),
        ("expected_referee_source_digest", expected_referee_source_digest),
    ):
        if value is not None and (not isinstance(value, str) or _SHA256.fullmatch(value) is None):
            raise RefereeReleaseError(f"{name} must be a sha256 content identity")
    root = _canonical_root(release_root, name="release_root", create=False)
    root_info = root.stat()
    parent_info = root.parent.stat()
    if (
        root_info.st_uid != os.geteuid()
        or parent_info.st_uid != os.geteuid()
        or parent_info.st_mode & 0o022
    ):
        raise RefereeReleaseError(
            "release root and its publication parent must be validator-owned/private"
        )
    approved_data = _normalize_package_data(DEFAULT_PACKAGE_DATA) | _normalize_package_data(
        package_data
    )
    actual_files, actual_directories = _walk_release_tree(root)
    if RELEASE_MANIFEST not in actual_files:
        raise RefereeReleaseError("release has no canonical manifest")
    manifest_path = root / RELEASE_MANIFEST
    manifest_raw = _read_regular_nofollow(manifest_path, max_bytes=8 * 1024 * 1024)
    if not manifest_raw.endswith(b"\n"):
        raise RefereeReleaseError("release manifest is not canonically encoded")
    manifest = _strict_json_object(manifest_raw, source=manifest_path)
    if set(manifest) != {
        "files",
        "package_data",
        "policy",
        "referee_source_digest",
        "schema",
        "tree_digest",
    }:
        raise RefereeReleaseError("release manifest has unexpected or missing fields")
    if manifest.get("schema") != RELEASE_SCHEMA or manifest.get("policy") != RELEASE_POLICY:
        raise RefereeReleaseError("release manifest schema/policy is unsupported")
    if manifest.get("package_data") != sorted(approved_data):
        raise RefereeReleaseError("release manifest package-data policy is not approved")
    if manifest_raw != _canonical_json(manifest) + b"\n":
        raise RefereeReleaseError("release manifest is not canonical JSON")
    files = _manifest_release_files(manifest.get("files"), package_data=approved_data)
    manifest_paths = {entry.path for entry in files}
    expected_files = manifest_paths | {RELEASE_MANIFEST}
    if actual_files != expected_files:
        missing = sorted(expected_files - actual_files)
        extra = sorted(actual_files - expected_files)
        raise RefereeReleaseError(
            f"release filesystem differs from manifest (missing={missing!r}, extra={extra!r})"
        )
    required_directories: set[str] = set()
    for path in manifest_paths:
        pure = PurePosixPath(path)
        for index in range(1, len(pure.parts)):
            required_directories.add(PurePosixPath(*pure.parts[:index]).as_posix())
    if actual_directories != required_directories:
        raise RefereeReleaseError("release contains unexpected or missing directories")

    payloads: dict[str, bytes] = {}
    for entry in files:
        payload = _read_regular_nofollow(
            root / PurePosixPath(entry.path), max_bytes=max(entry.size, 1)
        )
        identity_payload = _normalized_release_payload(entry.path, payload)
        if len(payload) != entry.size or _sha256(identity_payload) != entry.sha256:
            raise RefereeReleaseError(f"release file identity mismatch: {entry.path}")
        payloads[entry.path] = payload
    if not REQUIRED_RUNTIME_FILES.issubset(payloads):
        missing = sorted(REQUIRED_RUNTIME_FILES.difference(payloads))
        raise RefereeReleaseError(f"release lacks required OCI runtime files: {missing!r}")

    identity = {
        "files": [entry.as_manifest_row() for entry in files],
        "package_data": sorted(approved_data),
        "policy": RELEASE_POLICY,
        "schema": RELEASE_SCHEMA,
    }
    tree_digest = _sha256(_canonical_json(identity))
    source_digest = _referee_source_digest(payloads)
    if manifest.get("tree_digest") != tree_digest:
        raise RefereeReleaseError("release manifest tree digest is incorrect")
    if manifest.get("referee_source_digest") != source_digest:
        raise RefereeReleaseError("release manifest referee source digest is incorrect")
    receipt_payload = payloads.get(_RECEIPT_MODULE)
    if receipt_payload is None:
        raise RefereeReleaseError(f"release lacks {_RECEIPT_MODULE}")
    spans = _receipt_literal_spans(receipt_payload)
    receipt_values = {name: value for name, (_start, _end, value) in spans.items()}
    if receipt_values != {
        "APPROVED_REFEREE_SOURCE_DIGEST": source_digest,
        "APPROVED_REFEREE_TREE_DIGEST": tree_digest,
    }:
        raise RefereeReleaseError(
            "published referee approved digest literals do not match its manifest"
        )
    if expected_tree_digest is not None and tree_digest != expected_tree_digest:
        raise RefereeReleaseError(
            f"release tree identity mismatch: {tree_digest!r} != {expected_tree_digest!r}"
        )
    if (
        expected_referee_source_digest is not None
        and source_digest != expected_referee_source_digest
    ):
        raise RefereeReleaseError(
            "release referee source identity mismatch: "
            f"{source_digest!r} != {expected_referee_source_digest!r}"
        )
    return RefereeSourceRelease(
        root=root,
        tree_digest=tree_digest,
        referee_source_digest=source_digest,
        files=files,
        package_data=tuple(sorted(approved_data)),
    )
